- name: Variable from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
    - name: Print out from files
      ansible.builtin.debug:
        msg: "Hi i am {{Student}}, i am learning {{learning}} from trainer {{trainer}}, The Course duration {{Duration}}."