- name: Variables form Prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter username
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: true
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, username is: {{USERNAME} and password is: {{PASSWORD}}}"