- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user name is exist or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true
  
  - name: print user info
    ansible.builtin.debug:
      msg: "user id: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0 #condition 


  - name: print information
    ansible.builtin.debug:
      msg: "hello friend"