- name: check number
  hosts: localhost
  vars_prompt:
  - name: checking number
    prompt: Please enter number
    private: no

  tasks:
  - name: check number is lessthan 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 10"
    when: number | int < 10