- name: default value
  hosts: localhost
  tasks:
  - name: check default value
    ansible.builtin.debug:
      msg: "hello, {{ course| default('devops')}}"

- name: upper case
  hosts: localhost
  vars:
    message: "Hi, i am krishna"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: " {{ message | upper }}"

- name: lower case
  hosts: localhost
  vars:
    message: "HI, I am learning AWS"
  tasks:
  - name: convert in lower case
    ansible.builtin.debug:
      msg: "{{ message | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [10, 20, 20, 30 ,40, 40, 50]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ number | unique }}"