- name: default value
  hosts: localhost
  tasks:
  - name: check default value
    ansible.builtin.debug:
      msg: "hello, {{ course| default('devops')}}"

- name: upper case
  hosts: localhost
  vars:
    message: "Hi, i am krishna"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: " {{ message | upper }}"

- name: lower case
  hosts: localhost
  vars:
    message: "HI, I am learning AWS"
  tasks:
  - name: convert in lower case
    ansible.builtin.debug:
      msg: "{{ message | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [10, 20, 20, 30 ,40, 40, 50]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: min and max
  hosts: localhost
  vars:
    numbers: [100, 250, 35, 1000, 555,689]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "Min number is : {{ numbers | min}} and Max number is: {{ numbers | max}}"

- name: max and min
  hosts: localhost
  vars_prompt:
  - name: numbers
    prompt: Please enter numbers
    private: no
  tasks:
  - name: print max and min
    ansible.builtin.debug:
      msg: "Max number is: {{ numbers | max }} and Min number is: {{ numbers | min }}"

- name: convert disc to items
  hosts: localhost
  vars:
    my_dict:
      Course: DevOps with aws
      Trainer: SivaKumar M
      Duration: 4Months
      Timings: 7am to 9am
  tasks:
  - name: print list before convert
    ansible.builtin.debug:
      msg: "Here is the list before convert: {{my_dict}}"